[project]
name = "test-loguru-can-write-only-to-the-file"
version = "0.1.0"
description = "Test that we can stop loguru from writing to the console, but still write to a file"
requires-python = "==3.8.15"
dependencies = [
  "loguru",
]
