[project]
name = "test-loguru-shares-output"
version = "0.1.0"
description = "Test that loguru from multiple packages creates just one log"
requires-python = "==3.8.15"
dependencies = [
  "loguru",
]
