[project]
name = "test-loguru-can-change-log-level"
version = "0.1.0"
description = "Test that we can set the log level as we wish"
readme = "README.md"
requires-python = "==3.8.15"
dependencies = [
  "loguru",
  "typer",
]
