[project]
name = "test-loguru-writes-to-a-file"
version = "0.1.0"
description = "Will loguru send output to a file, again, from multiple modules?"
readme = "README.md"
requires-python = "==3.8.15"
dependencies = [
  "loguru",
]
